const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGOUT: 'LOGOUT',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    GET_POSTS: "GET_POSTS",
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_ADMIN: "GET_POSTS_ADMIN",
    GET_NEW_POST: "GET_NEW_POST",
    EDIT_DATA: "EDIT_DATA",
    RESET_DATAEDIT: "RESET_DATAEDIT",
    GET_OUTSTANDING: "GET_OUTSTANDING",

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',
    GET_DICTRICTS: 'GET_DICTRICTS',
    UPDATE_POST_LIKE_STATUS: 'UPDATE_POST_LIKE_STATUS',
    UPDATE_POST_LIKE_STATUS_SUCCESS: 'UPDATE_POST_LIKE_STATUS_SUCCESS',
    UPDATE_POST_LIKE_STATUS_FAILURE: 'UPDATE_POST_LIKE_STATUS_FAILURE',
    SET_SHOW_FAVORITES: 'SET_SHOW_FAVORITES',
    SAVE_FAVORITE_POST: 'SAVE_FAVORITE_POST',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE: 'DELETE_POST_FAILURE',
    POST_OPERATION_FAILED: 'POST_OPERATION_FAILED',
    // USER
    GET_CURRENT: 'GET_CURRENT',
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    USER_OPERATION_FAILED: 'USER_OPERATION_FAILED',
    FETCH_USERS: 'FETCH_USERS',
    UPDATE_USER: 'UPDATE_USER'
}

export default actionTypes